---
global:
  dockerRegistry: public.ecr.aws

image:
  repository: "m4z9c2w0/opensearch-treadstone"
  tag: "4777332356"
  pullPolicy: "IfNotPresent"

majorVersion: "2"

nodeGroup: "machinelearning"

roles:
  - ml

replicas: 2

opensearchJavaOpts: "-Xmx16G -Xms16G"

resources:
  requests:
    cpu: "4"
    memory: "32Gi"
